title: Bai tap tuan 5
description: Code
template:
  repo: bai-tap-tuan-5-template
  name: bai-tap-tuan-5
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
